### ISSUE TITLE
first-timers-only: Add test to verify SpeechKITT.displayRecognizedSentence() works well

### ISSUE THREAD

**Issue by TalAter** [TalAter/SpeechKITT#15]
#### first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Thank you for your help :heart:

#### Background

Speech KITT provides a GUI to sites using Speech Recognition.

One of its newer features let it show the last sentence the user said in the GUI. This feature is turned on by calling `SpeechKITT.displayRecognizedSentence()` ([docs](https://github.com/TalAter/SpeechKITT/tree/master/docs#displayrecognizedsentencenewstatetrue)).

Speech KITT learns about these sentences when the Speech Recognition engine calls `SpeechKITT.setRecognizedSentence()` ([docs](https://github.com/TalAter/SpeechKITT/tree/master/docs#setrecognizedsentencesentence)).

The sentence is displayed inside a new `span` element with the id `skitt-listening-text__recognized-sentence` which contains the text said.

````html
<span id="skitt-listening-text__recognized-sentence">What the user said</span>
````

#### The Issue

While the test specs test that the functionality of `SpeechKITT.displayRecognizedSentence()` works, it does not currently test to verify that it creates a `span` with the id `skitt-listening-text__recognized-sentence`.

Add test specs that verify the following:

````javascript
  it('should create a span node', func);
  it('should create the new node with the id `skitt-listening-text__recognized-sentence`', func);
````

This should be added into the file `/test/spec/UISpec.js` into the following test suite:
````javascript
describe('SpeechKITT.displayRecognizedSentence', function() {
````

In your specs, you can use jQuery using the `$` sign to fetch the `span` element.

#### Contributing to Speech KITT

- [ ] Fork the repository from the [Speech KITT GitHub page](https://github.com/TalAter/SpeechKITT).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/SpeechKITT.git`
- [ ] Make sure you have *node.js* and *npm* installed on your machine. You can use this [guide](https://docs.npmjs.com/getting-started/installing-node) for help.
- [ ] Install all of Speech KITT's development dependencies with npm. `$ cd SpeechKITT; npm install`
- [ ] Run grunt to make sure everything runs smoothly `$ grunt`
- [ ] Code, code, code.
- [ ] Run `$ grunt` after making changes to verify that everything still works and run the build process. Alternatively, you can just run `$ grunt watch` once, and leave that process running. It will continuously run all the tests and build the files every time you make a change to one of Speech KITT's files. It will even *beep* if you make an error, and help you debug it.:+1:
- [ ] Before committing your changes, the last step must always be running `$ grunt`. This makes sure everything works, and all files are kept up to date with your changes.
- [ ] Once you've made sure all your changes work correctly, and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/SpeechKITT](https://github.com/YOUR-USER-NAME/SpeechKITT)) and create a pull request for your changes.
- [ ] Makes sure your pull request describes exactly what you changed and references this issue (just include the issue number in the title like this: #49)

#### About the tests

Speech KITT is tested using [Jasmine](http://jasmine.github.io/2.0/introduction.html).

BasicSpec.js and UISpec.js contain a series of spec groups (e.g. `describe('a spec group', function() {})`) which each contain 1 or more specs (e.g. `it('should do stuff', function() {})`). Some of the spec groups also contain some code which runs before each spec (`beforeEach(function() {})`).

To simulate Speech Recognition in the testing environment, Speech KITT uses a mock object called [Corti](https://github.com/TalAter/Corti) which mocks the browser's SpeechRecognition object. Corti also adds a number of utility functions to the SpeechRecognition object which simulate user actions (e.g. `say('Hello there')`), and allow checking the SpeechRecognition's status (e.g. `isListening() === true`).

**Comment by dargaCode** [comment]
Hi @TalAter, I've been looking around for quite some time for an issue I could handle. 

I've spent the last couple of days learning about grunt and jasmine and I'm going to give this a try!

**Comment by TalAter** [comment]
Awesome @dargaCode :+1: 

Please feel free to ask if you have any questions.

**Comment by TalAter** [comment]
Looks great!

Thank you for the help, and congrats on your first :octocat: pull request.

**Comment by dargaCode** [comment]
AHHHHH THANK YOU SO MUCH!
So many issues I found before this one were so intimidating and seemed to include so little information. 
It's clear that you put a lot of care into setting aside this task, and documenting the steps required. 

Thank you also for your advice as I was going through this and feeling so doubtful of what I was doing =D
