### ISSUE TITLE
GUI is not hidden after invoking hide() method 

### ISSUE THREAD

**Issue by mcollovati** [TalAter/SpeechKITT#20]
## Expected Behavior
After invoking hide() method the gui should not be visible.

## Current Behavior
After invoking hide() method the css class `skitt-ui--hidden` is applied but the gui is still visible.
All themes seem to have same behaviour.

## Possible Solution
The problem could be fixed with a stronger rule 

```
#skitt-ui.skitt-ui--hidden {
    display: none !important;
}
```

## Your Environment
* Version used: 0.3.0
* Browser Name and version: Google chrome 51.0.2704.63
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by mcollovati** [comment]
May I close this issue?

**Comment by TalAter** [comment]
Thank you 👍
