### ISSUE TITLE
Demo for "follow up questions"

### ISSUE THREAD

**Issue by thurt** [TalAter/SpeechKITT#23]
> It can even be used to carry a natural conversation with the user, asking questions the user can answer with his voice, and then asking follow up questions.

It is not clear to me how I would be able to implement this naturally. 
Is there a demo for this type of thing?

## Expected Behavior
I envision a demo for this claim might go something like:
speechkitt: "Who do you want to look up in the database?"
person: "John Jones"
speechkitt: "Do you mean [1] John Jonnes or [2] John Jones?"
person: "Number 2"
speechkitt: "Right. John Jones. Here is the info: ..."

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by TalAter** [comment]
Thank you, that is a great idea. 👍 

I plan on creating a new tutorial for annyang, and this could be something to try in it.

As for your problem at hand:
I could see some sort of decision tree, where the function called by each matched sentence would register new commands to listen for. You would also need to write the machine's reply using SpeechKITT.setInstructionsText()

**Comment by thurt** [comment]
That's good to hear about a potential demo! Thanks for letting me know your
ideas.

I didnt see any immediate way to do this with the current methods, so I
initially thought a graph/decision tree would be needed. I can definitely
imagine how this might work from your suggestions.

**Comment by LukeMcLachlan** [comment]
@TalAter any sort of update on this proposed conversation tree? It would be an amazing feature to release. Thanks.
