### ISSUE TITLE
Cannot appendChild error

### ISSUE THREAD

**Issue by Antmanofgod** [TalAter/SpeechKITT#37]
I have received the following error while trying to use SpeechKITT with annyang.

Uncaught TypeError: Cannot read property 'appendChild' of null
    at n (speechkitt.min.js:6)
    at Object.render (speechkitt.min.js:6)
    at Object.vroom (speechkitt.min.js:6)
    at index.html:25

I'm not sure what I'm missing but I've tried to use the SpeechKITT GUI on two separate sites with the same result.

Any help would be appreciated, thank you.

**Comment by TalAter** [comment]
Hi @Antmanofgod 

My apologies for the slow response. Do you still need help with this issue? If so, please reopen this task and provide a few more details. Perhaps some sample code.

One possible idea. Are you trying to run the code about in the <head> of the page? I noticed that the only two places SpeechKITT calls appendChild is when trying to access `document.body` which is `null` if executed too early. Definitely something I should fix!

**Comment by nafees55** [comment]
@TalAter Yes if we try to call SpeechKITTrender() or SpeechKITT.vroom() in the head tag of the page. It will through the same error (Uncaught TypeError: Cannot read property 'appendChild' of null). i have tried to use in the body tag. It's working.
