### ISSUE TITLE
 I would interested to understand this in terms of security

### ISSUE THREAD

**Issue by nseminer** [TalAter/SpeechKITT#45]
Does this send voice to other website to do the conversion or is it a isolated engine.

I am afraid to use this if it is sending voice to some other service.

It would be helpful if you can provide the architecture details of this.

 --

**Comment by TalAter** [comment]
SpeechKITT does not do any speech recognition. It is just the UI layer on top of other Speech Recognition engines you might use.

The engines it is most often used with are part of the browser itself which usually does send it to the web for processing (e.g., Google Chrome does the speech recognition on Google's servers).
