### ISSUE TITLE
How can I know that what I said was sent for recognition?

### ISSUE THREAD

**Issue by ceides9497** [TalAter/SpeechKITT#48]
I need know when the request for recognition is sent to cloud

**Comment by TalAter** [comment]
That is up to whatever speech recognition you are using. SpeechKITT merely provides a visual UI for the user to whatever Speech Recognition you are using.

But just to point you in the right direction, if you are using webkitSpeechRecognition in Chrome, I believe the [speechend](https://w3c.github.io/speech-api/#eventdef-speechrecognition-speechend) event is the one you are looking... having said that, I believe that event was implemented incorrectly in Chromium as I reported here - https://bugs.chromium.org/p/chromium/issues/detail?id=572697#c_ts1457337909

I think this doesn't leave you with any options to do exactly what you are looking for.

**Comment by ceides9497** [comment]
Thanks... and sorry... I wanted this issue in Annyang project
