### ISSUE TITLE
speechkitt.js:330 Uncaught TypeError: _root.clearTimeout is not a function

### ISSUE THREAD

**Issue by duxiaocheng** [TalAter/SpeechKITT#49]
There is an unexpected error as title shown.
 speechkitt.js:330 Uncaught TypeError: _root.clearTimeout is not a function
    at Object.onStart (speechkitt.js:330)
    at annyang.min.js:13
    at Array.forEach (<anonymous>)
    at S (annyang.min.js:13)
    at SpeechRecognition.a.onstart (annyang.min.js:13)

## Steps to Reproduce (for bugs)

1. npm install speechkitt
2. start speechkitt
3. report the error as title
4.

## Your Environment

* Version used: speechkitt@1.0.0
* Browser Name and version: chrome 73.0.3683.103
* Operating System and version (desktop or mobile): desktop/centos7.0
* Link to your project:
    SpeechKITT.annyang();
    SpeechKITT.setStartCommand(function() {
      console.log("start speech recognition...");
      annyang.start();
    });

**Comment by TalAter** [comment]
My guess based on the information provided is that this issue is because you are installing it via npm. 

SpeechKITT was built years ago, and wasn't really meant to be installed via npm. Try including the script in your page and calling it instead.
